apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: name
        value: "HemanthKumar"
      - name: location
        value: khammam
      - name: state
        value: telangana
      - name: country
        value: INDIA