apiVersion: v1
kind: Service
metadata:
  name:  nginx
spec:
  selector:
    app:  3-tier
    project: expense
    module: backend
    environment: dev
  type: ClusterIP
  ports:
  - name:  nginx-svc-port
    protocol: TCP
    port:  80
    targetPort:  80