kind: Service
apiVersion: v1
metadata:
  name:  nginx-nodeport
spec:
  selector:
    app:  3-tier
    environment: dev
    project: expense
    module: backend
  type:  NodePort
  ports:
  - name:  nginx-svc-port
    protocol: TCP
    port:  80
    targetPort:  80