apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    apps: nginx
    tier: 3-tier
    module: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      apps: nginx
      tier: 3-tier
      module: frontend
  template:
    metadata:
      labels:
        apps: nginx
        tier: 3-tier
        module: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
