apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-02a0c125bc396a6a4     # created volume ID we need to provide here
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set. No default storage class is applied.
  volumeName: ebs-static-pv   # must match the name with PV name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static-volume-creation
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx
    image: nginx
    # command: ["/bin/sh"]
    # args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage-static  # must match the name in volumes.
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage-static  # must match the name in volumeMounts.
    persistentVolumeClaim:
      claimName: ebs-static-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    purpose: ebs-static-volume-creation
  ports:
    - name: nginx-svc-ports
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30010