apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-efs-sc-dynamic
reclaimPolicy: Retain
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  provisioningMode: efs-ap
  directoryPerms: "700"
  fileSystemId: fs-00cbb3f0e4313c700
  basePath: "/expense"